variables:
  ENV_NAME: prod
  CI_REGISTRY_IMAGE: registry1.hoangbaoochii.id/galaxy/galaxy-landing
  CI_REGISTRY: registry1.hoangbaoochii.id
  
build:
  image: docker:25.0.1
  before_script:
    - docker info
    - docker images
    - echo $REGISTRY_PUSH_USER
    - echo $REGISTRY_PUSH_PASSWORD
    - echo $CI_REGISTRY
    - docker login -u "$REGISTRY_PUSH_USER" -p "$REGISTRY_PUSH_PASSWORD" "$CI_REGISTRY"
  script:
    - export APP_VERSION=$ENV_NAME-$(date +'%Y-%m-%d_%H-%M-%S')-`[ -n "$CI_COMMIT_TAG" ] && echo $CI_COMMIT_TAG || echo $CI_COMMIT_SHORT_SHA` && echo $APP_VERSION
    - docker build -t "$CI_REGISTRY_IMAGE:$APP_VERSION" -t "$CI_REGISTRY_IMAGE"  . -f Dockerfile
    - docker push "$CI_REGISTRY_IMAGE:$APP_VERSION"
  services:
    - name: docker:25.0.1-dind
      alias: docker
  allow_failure: false


